### PR TITLE
Add more of the Vec API to *BufferVec

### PR DESCRIPTION
**Pull request by james7132**
This PR does the following:

 * Implements `Deref`, `DerefMut`, and `Extend` on all of the *BufferVec types using the backing slice of the Vec. Extend adheres to the "panic on capacity overflow" that `push` does.
 * Exposes `pop`, `swap_remove`, and `truncate` from the underlying Vec. These should either shrink or keep the Vec's length, so it shouldn't require `RenderResources`.
 
These changes allow use of the buffer Vecs as an authoritative source of truth rather than a temporary buffer, and can remove the need for a full buffer copy when used like so. This should be very useful for use cases with a large amount of mutation on the CPU side (i.e. CPU particle systems).

### CODE REVIEW

**Comment by mtsr** [comment]
This seems useful to me! Which traits and functions do we support, though, and which not? 

I might also have a use case for this: In the nbody example for bevy_polyline I keep a window of the last 8096 points of the line to draw a trail. This really needs a smart way of updating and drawing, because of the amount of data transferred otherwise. I'm currently thinking of treating the GPU buffer as a ringbuffer and doing two drawcalls. One from the start of the window (which may be anywhere in the buffer) to the end of the buffer and one from the start of the buffer to the end of the window (which again can be anywhere in the buffer). That way I'd only have to copy new points and change the offset. I'll see what I need to support this efficiently sometime in the next few weeks.

**Comment by james7132** [comment]
> This seems useful to me! Which traits and functions do we support, though, and which not?

I only added the ones I needed for CPU particle systems to work. The only safe ones to use are ones that do not expand the Vec as it might grow larger than the allocated buffer size. Though in retrospect, we could just make it Deref to the underlying Vec, and do a size check/reallocation before writing out to the target buffers.

**Comment by cart** [comment]
It is worth calling out that I'm considering removing the vec storage entirely in favor of direct writes to a mapped buffer. This would be slightly less flexible, but should be faster. If that happens, we'd need to change how these are implemented.

**Comment by james7132** [comment]
So long as there's an easier way to map Pod Vecs and buffers, potentially allowing resizing, sounds good to me.

**Pull request closed without merging**
